[package]
name = "hexreader"
version = "1.3.0"
edition = "2021"

[dependencies]

[profile.release]
opt-level = 3
strip = "symbols"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
